apiVersion: apps/v1
kind: Deployment
metadata:
  name: votes-api
  namespace: peek
  labels:
    app: votes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votes-api
  template:
    metadata:
      name: votes-api
      labels:
        app: votes-api
    spec:
      containers:
        - name: votes-api
          image: peek-votes-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: votes-ui-secrets
                  key: POSTGRES_HOST
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: votes-ui-secrets
                  key: PORT
            - name: OPTION_A
              valueFrom:
                secretKeyRef:
                  name: votes-ui-secrets
                  key: OPTION_A
            - name: OPTION_B
              valueFrom:
                secretKeyRef:
                  name: votes-ui-secrets
                  key: OPTION_B
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: votes-api-service
  namespace: peek
  labels:
    app: votes-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: votes-api
  type: NodePort
